# Generated by Django 5.2.9 on 2026-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
