# Generated by Django 5.2.9 on 2026-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_quizcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option1_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option2_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option3_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='option4_image',
            field=models.ImageField(blank=True, null=True, upload_to='options/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('TEXT', 'Text Answer')], default='MCQ', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='round_type',
            field=models.CharField(choices=[('ROUND1', 'Round 1'), ('GOOGLER', 'Googler Round')], default='ROUND1', max_length=20),
        ),
    ]
